@extends('layouts.app')
@section('title','Jadwal Pelatihan')
@section('page-heading','Jadwal Pelatihan')
@section('page-description')Tentukan jadwal kelas dan trainer terlebih dahulu sebelum customer didaftarkan.@endsection
@section('content')
<div class="space-y-6">
@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-5 py-4 text-sm text-green-800">{{ session('success') }}</div>@endif
@if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-800">{{ session('error') }}</div>@endif
<div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-xl font-semibold text-slate-900">Jadwal yang Tersedia</h2><p class="mt-1 text-sm text-slate-500">Setiap jadwal memiliki trainer, waktu, lokasi, dan kapasitas.</p></div><div class="flex gap-2"><a href="{{ route('trainers.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium text-slate-700">Kelola Trainer</a><a href="{{ route('training-schedules.create') }}" class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">+ Buat Jadwal</a></div></div>
<form method="GET" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex flex-wrap gap-3"><input name="search" value="{{ request('search') }}" placeholder="Cari pelatihan, trainer, atau lokasi..." class="min-w-[280px] flex-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm"><select name="status" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Semua status</option>@foreach($statusLabels as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Cari</button></div></form>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr>
@foreach([['training','Pelatihan'],['trainer','Trainer'],['training_date','Tanggal'],['start_time','Jam Mulai'],['end_time','Jam Selesai'],['status','Status']] as [$c,$l])<th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">@include('components.table-sort',['label'=>$l,'column'=>$c])</th>@endforeach
<th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Peserta</th><th class="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wide text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-slate-200">
@forelse($schedules as $s)<tr class="hover:bg-slate-50"><td class="px-6 py-5 font-semibold text-slate-900">{{ $s->training->name }}</td><td class="px-6 py-5 text-sm text-slate-700">{{ $s->trainer->name }}</td><td class="px-6 py-5 text-sm text-slate-700">{{ $s->training_date->format('d M Y') }}</td><td class="px-6 py-5 text-sm text-slate-700">{{ substr($s->start_time,0,5) }}</td><td class="px-6 py-5 text-sm text-slate-700">{{ substr($s->end_time,0,5) }}</td><td class="px-6 py-5"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{{ $statusLabels[$s->status]??$s->status }}</span></td><td class="px-6 py-5 text-sm text-slate-700">{{ $s->active_registrations_count }}@if($s->capacity) / {{ $s->capacity }}@endif</td><td class="px-6 py-5"><div class="flex justify-end gap-2"><a href="{{ route('training-schedules.show',$s) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">Detail</a><a href="{{ route('training-schedules.edit',$s) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">Edit</a></div></td></tr>@empty<tr><td colspan="8" class="px-6 py-12 text-center text-sm text-slate-500">Belum ada jadwal pelatihan.</td></tr>@endforelse</tbody></table></div><div class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-6 py-4"><form method="GET" class="flex items-center gap-2 text-sm text-slate-600">@foreach(request()->except('per_page','page') as $k=>$v)<input type="hidden" name="{{ $k }}" value="{{ $v }}">@endforeach<span>Tampilkan</span><select name="per_page" onchange="this.form.submit()" class="rounded-lg border border-slate-300 px-3 py-2">@foreach($options as $o)<option value="{{ $o }}" @selected($per===$o)>{{ $o }}</option>@endforeach</select></form>{{ $schedules->links() }}</div></div></div>
@endsection
