@extends('layouts.app')
@section('title','Detail Jadwal Pelatihan')
@section('page-heading','Detail Jadwal Pelatihan')
@section('page-description')Detail batch pelatihan dan peserta yang terdaftar.@endsection
@section('content')
<div class="space-y-6">
@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-5 py-4 text-sm text-green-800">{{ session('success') }}</div>@endif
@if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-800">{{ session('error') }}</div>@endif
<div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-semibold text-slate-900">{{ $trainingSchedule->training->name }}</h2><p class="mt-1 text-sm text-slate-500">Trainer: {{ $trainingSchedule->trainer->name }}</p></div><div class="flex gap-2"><a href="{{ route('training-schedules.edit',$trainingSchedule) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium">Edit</a><a href="{{ route('training-schedules.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium">Kembali ke Jadwal</a></div></div>
<div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Tanggal</div><div class="mt-2 font-semibold text-slate-900">{{ $trainingSchedule->training_date->format('d M Y') }}</div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Waktu</div><div class="mt-2 font-semibold text-slate-900">{{ substr($trainingSchedule->start_time,0,5) }} – {{ substr($trainingSchedule->end_time,0,5) }}</div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Lokasi</div><div class="mt-2 font-semibold text-slate-900">{{ $trainingSchedule->location ?: '-' }}</div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Kapasitas</div><div class="mt-2 font-semibold text-slate-900">{{ $trainingSchedule->registrations->where('status','!=','cancelled')->count() }}{{ $trainingSchedule->capacity ? ' / '.$trainingSchedule->capacity : '' }}</div></div></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-6 py-5"><div><h3 class="font-semibold text-slate-900">Peserta Terdaftar</h3><p class="mt-1 text-sm text-slate-500">Customer didaftarkan ke jadwal yang sudah ditentukan ini.</p></div><a href="{{ route('registrations.create',['training_schedule_id'=>$trainingSchedule->id]) }}" class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">+ Daftarkan Customer</a></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr><th class="px-6 py-4 text-left text-xs uppercase text-slate-500">Customer</th><th class="px-6 py-4 text-left text-xs uppercase text-slate-500">No. Registrasi</th><th class="px-6 py-4 text-left text-xs uppercase text-slate-500">Status</th><th class="px-6 py-4 text-right text-xs uppercase text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-slate-200">@forelse($trainingSchedule->registrations as $registration)<tr><td class="px-6 py-5"><a class="font-semibold text-slate-900 hover:underline" href="{{ route('customers.show',$registration->customer) }}">{{ $registration->customer->name }}</a><div class="text-xs text-slate-400">{{ $registration->customer->customer_code }}</div></td><td class="px-6 py-5 text-sm text-slate-700">{{ $registration->registration_number ?: '-' }}</td><td class="px-6 py-5"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{{ ucfirst($registration->status) }}</span></td><td class="px-6 py-5 text-right"><a href="{{ route('registrations.edit',$registration) }}" class="text-sm font-medium text-slate-700 hover:underline">Edit</a></td></tr>@empty<tr><td colspan="4" class="px-6 py-12 text-center text-sm text-slate-500">Belum ada peserta.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
