@php
    $selectedCustomerId = old('customer_id', $selectedCustomerId ?? ($registration?->customer_id));
    $selectedScheduleId = old('training_schedule_id', $selectedScheduleId ?? ($registration?->training_schedule_id));
    $selectedStatus = old('status', $registration?->status ?? 'registered');
    $selectedAmount = old('amount', $registration?->amount);
@endphp
<form method="POST" action="{{ $action }}" class="space-y-6">@csrf @if($method!=='POST') @method($method) @endif
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-5"><div class="font-semibold text-red-800">Periksa data berikut:</div><ul class="mt-2 list-disc pl-5 text-sm text-red-700">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="grid gap-5 md:grid-cols-2">
<div><label class="mb-2 block text-sm font-medium">Customer *</label><select name="customer_id" required class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm"><option value="">Pilih customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((int)$selectedCustomerId===(int)$customer->id)>{{ $customer->name }} — {{ ucfirst($customer->status) }}</option>@endforeach</select><p class="mt-2 text-xs text-slate-500">Hanya Active dan Repeat Customer.</p></div>
<div><label class="mb-2 block text-sm font-medium">Jadwal Pelatihan *</label><select id="training_schedule_id" name="training_schedule_id" required class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm"><option value="">Pilih jadwal</option>@foreach($schedules as $schedule)<option value="{{ $schedule->id }}" data-price="{{ $schedule->training->price !== null ? (float)$schedule->training->price : '' }}" @selected((int)$selectedScheduleId===(int)$schedule->id)>{{ $schedule->training->name }} · {{ $schedule->training_date->format('d M Y') }} · {{ substr($schedule->start_time,0,5) }}-{{ substr($schedule->end_time,0,5) }} · {{ $schedule->trainer->name }}@if($schedule->location) · {{ $schedule->location }}@endif</option>@endforeach</select><p class="mt-2 text-xs text-slate-500">Tanggal dan jam berasal dari jadwal yang sudah dibuat admin.</p>@error('training_schedule_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="mb-2 block text-sm font-medium">Status *</label><select name="status" required class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm">@foreach(['registered'=>'Registered','confirmed'=>'Confirmed','completed'=>'Completed','cancelled'=>'Cancelled'] as $v=>$l)<option value="{{ $v }}" @selected($selectedStatus===$v)>{{ $l }}</option>@endforeach</select></div>
<div><label class="mb-2 block text-sm font-medium">Amount</label><input id="amount" type="number" min="0" step="0.01" name="amount" value="{{ $selectedAmount }}" class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm"><p class="mt-2 text-xs text-slate-500">Harga master training menjadi nilai awal.</p></div>
<div><label class="mb-2 block text-sm font-medium">No. Registrasi</label><input name="registration_number" value="{{ old('registration_number',$registration?->registration_number) }}" placeholder="Kosongkan untuk otomatis" class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm"></div>
<div class="md:col-span-2"><label class="mb-2 block text-sm font-medium">Catatan</label><textarea name="notes" rows="4" class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm">{{ old('notes',$registration?->notes) }}</textarea></div>
</div></div>
<div class="flex justify-end gap-2"><a href="{{ $registration ? route('registrations.index') : route('customers.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm">Batal</a><button class="rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">{{ $buttonLabel }}</button></div>
</form>
<script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('training_schedule_id'),a=document.getElementById('amount');if(!s||!a)return;s.addEventListener('change',()=>{const p=s.options[s.selectedIndex]?.dataset?.price;if(p) a.value=p;});});</script>
