@extends('layouts.app')
@section('title','Pendaftaran Training')
@section('page-heading','Pendaftaran Training')
@section('page-description')Catat customer yang mengikuti jadwal pelatihan yang sudah ditentukan.@endsection
@section('content')
<div class="space-y-6">
@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-5 py-4 text-sm text-green-800">{{ session('success') }}</div>@endif
@if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-800">{{ session('error') }}</div>@endif
<div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-xl font-semibold text-slate-900">Pendaftaran Peserta</h2><p class="mt-1 text-sm text-slate-500">Customer didaftarkan ke jadwal yang telah dibuat, bukan menentukan tanggal sendiri.</p></div><div class="flex gap-2"><a href="{{ route('training-schedules.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium">Lihat Jadwal</a><a href="{{ route('registrations.create') }}" class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">+ Daftarkan Customer</a></div></div>
<form method="GET" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="grid gap-3 md:grid-cols-[minmax(280px,1fr)_180px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Cari nomor, customer, training, trainer..." class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm"><select name="status" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm"><option value="">Semua status</option>@foreach($statusLabels as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Filter</button></div></form>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr>
@foreach([['registration_number','No. Registrasi'],['customer','Customer'],['training','Pelatihan'],['schedule','Jadwal'],['status','Status'],['amount','Amount']] as [$c,$l])<th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">@include('components.table-sort',['label'=>$l,'column'=>$c])</th>@endforeach<th class="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wide text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-slate-200">
@forelse($registrations as $r)<tr class="hover:bg-slate-50"><td class="px-6 py-5 text-sm font-semibold text-slate-900">{{ $r->registration_number ?: '-' }}</td><td class="px-6 py-5"><a href="{{ route('customers.show',$r->customer) }}" class="font-semibold text-slate-900 hover:underline">{{ $r->customer->name }}</a><div class="text-xs text-slate-400">{{ $r->customer->customer_code }}</div></td><td class="px-6 py-5 text-sm text-slate-700">{{ $r->training->name }}</td><td class="px-6 py-5 text-sm text-slate-700">@if($r->schedule)<a class="hover:underline" href="{{ route('training-schedules.show',$r->schedule) }}">{{ $r->schedule->training_date->format('d M Y') }} · {{ substr($r->schedule->start_time,0,5) }}<div class="text-xs text-slate-400">{{ $r->schedule->trainer->name }}</div></a>@else<span class="text-slate-400">Jadwal lama</span>@endif</td><td class="px-6 py-5"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{{ $statusLabels[$r->status]??$r->status }}</span></td><td class="px-6 py-5 text-sm text-slate-700">{{ $r->amount!==null?'Rp '.number_format((float)$r->amount,0,',','.'):'-' }}</td><td class="px-6 py-5 text-right"><a href="{{ route('registrations.edit',$r) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">Edit</a></td></tr>@empty<tr><td colspan="7" class="px-6 py-12 text-center text-sm text-slate-500">Belum ada pendaftaran.</td></tr>@endforelse</tbody></table></div><div class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-6 py-4"><form method="GET" class="flex items-center gap-2 text-sm text-slate-600">@foreach(request()->except('per_page','page') as $k=>$v)@if(is_scalar($v))<input type="hidden" name="{{ $k }}" value="{{ $v }}">@endif @endforeach<span>Tampilkan</span><select name="per_page" onchange="this.form.submit()" class="rounded-lg border border-slate-300 px-3 py-2">@foreach($perPageOptions as $o)<option value="{{ $o }}" @selected($perPage===$o)>{{ $o }}</option>@endforeach</select></form>{{ $registrations->links() }}</div></div></div>
@endsection
