@php
    $customerValue = old('customer_id', $followUp?->customer_id ?? $selectedCustomerId ?? null);
    $assignedValue = old('assigned_to', $followUp?->assigned_to ?? auth()->id());
    $followUpAt = old('follow_up_at', $followUp?->follow_up_at?->format('Y-m-d\TH:i') ?? now()->addDay()->format('Y-m-d\TH:i'));
    $priority = old('priority', $followUp?->priority ?? 'normal');
@endphp
<div class="grid gap-5 md:grid-cols-2">
<div class="md:col-span-2"><label for="customer_id" class="mb-2 block text-sm font-medium text-slate-700">Customer *</label><select id="customer_id" name="customer_id" required class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm"><option value="">Pilih customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)$customerValue===(string)$customer->id)>{{ $customer->name }} — {{ $customer->customer_code }} ({{ ucfirst($customer->status) }})</option>@endforeach</select>@error('customer_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label for="title" class="mb-2 block text-sm font-medium text-slate-700">Judul *</label><input id="title" name="title" value="{{ old('title',$followUp?->title) }}" required placeholder="Contoh: Follow up kebutuhan pelatihan" class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm">@error('title')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label for="follow_up_at" class="mb-2 block text-sm font-medium text-slate-700">Tanggal & Waktu *</label><input id="follow_up_at" type="datetime-local" name="follow_up_at" value="{{ $followUpAt }}" required class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm">@error('follow_up_at')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label for="priority" class="mb-2 block text-sm font-medium text-slate-700">Prioritas *</label><select id="priority" name="priority" required class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm">@foreach(['low'=>'Low','normal'=>'Normal','high'=>'High'] as $value=>$label)<option value="{{ $value }}" @selected($priority===$value)>{{ $label }}</option>@endforeach</select></div>
<div><label for="assigned_to" class="mb-2 block text-sm font-medium text-slate-700">PIC</label><select id="assigned_to" name="assigned_to" class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm"><option value="">Belum ditentukan</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)$assignedValue===(string)$user->id)>{{ $user->name }}</option>@endforeach</select></div>
<div class="md:col-span-2"><label for="description" class="mb-2 block text-sm font-medium text-slate-700">Catatan</label><textarea id="description" name="description" rows="5" placeholder="Tuliskan rencana atau hasil yang diharapkan..." class="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm">{{ old('description',$followUp?->description) }}</textarea></div>
</div>
