@extends('layouts.app')
@section('title','Trainer')
@section('page-heading','Trainer')
@section('page-description')Kelola trainer yang dapat ditugaskan ke jadwal pelatihan.@endsection
@section('content')
<div class="space-y-6">
@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-5 py-4 text-sm text-green-800">{{ session('success') }}</div>@endif
@if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-800">{{ session('error') }}</div>@endif
<div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-xl font-semibold text-slate-900">Daftar Trainer</h2><p class="mt-1 text-sm text-slate-500">Trainer digunakan saat membuat jadwal pelatihan.</p></div><a href="{{ route('trainers.create') }}" class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">+ Tambah Trainer</a></div>
<form method="GET" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex flex-wrap gap-3"><input name="search" value="{{ request('search') }}" placeholder="Cari trainer, email, atau telepon..." class="min-w-[280px] flex-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm"><input type="hidden" name="sort" value="{{ $sort }}"><input type="hidden" name="direction" value="{{ $direction }}"><input type="hidden" name="per_page" value="{{ $per }}"><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Cari</button></div></form>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr>
@foreach([['name','Nama'],['email','Email'],['phone','Telepon'],['is_active','Status']] as [$col,$label])<th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">@include('components.table-sort',['label'=>$label,'column'=>$col])</th>@endforeach
<th class="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wide text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-slate-200">
@forelse($trainers as $trainer)<tr class="hover:bg-slate-50"><td class="px-6 py-5 font-semibold text-slate-900">{{ $trainer->name }}</td><td class="px-6 py-5 text-sm text-slate-700">{{ $trainer->email ?: '-' }}</td><td class="px-6 py-5 text-sm text-slate-700">{{ $trainer->phone ?: '-' }}</td><td class="px-6 py-5">@if($trainer->is_active)<span class="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-700">Aktif</span>@else<span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">Nonaktif</span>@endif</td><td class="px-6 py-5"><div class="flex justify-end gap-2"><a href="{{ route('trainers.edit',$trainer) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700">Edit</a>@if(!$trainer->schedules()->exists())<form method="POST" action="{{ route('trainers.destroy',$trainer) }}" onsubmit="return confirm('Hapus trainer ini?')">@csrf @method('DELETE')<button class="rounded-lg border border-red-200 px-3 py-2 text-sm font-medium text-red-600">Hapus</button></form>@endif</div></td></tr>
@empty<tr><td colspan="5" class="px-6 py-12 text-center text-sm text-slate-500">Belum ada trainer.</td></tr>@endforelse</tbody></table></div><div class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-6 py-4"><form method="GET" class="flex items-center gap-2 text-sm text-slate-600">@foreach(request()->except('per_page','page') as $k=>$v)<input type="hidden" name="{{ $k }}" value="{{ $v }}">@endforeach<span>Tampilkan</span><select name="per_page" onchange="this.form.submit()" class="rounded-lg border border-slate-300 px-3 py-2">@foreach($options as $o)<option value="{{ $o }}" @selected($per===$o)>{{ $o }}</option>@endforeach</select></form>{{ $trainers->links() }}</div></div></div>
@endsection
